export const BASE_URL = "https://api.openweathermap.org/data/2.5/weather?"
export const BASE_URL_DAY = "https://api.openweathermap.org/data/2.5/forecast?"
export const KEY = "d66b30580c1005ed0f66d2c1486bb40d"
export const ICON = "http://openweathermap.org/img/w"
export const UNIT_TEMPERATURE = "units=metric"
export const LANG = "lang=pt_br"